parameters:
  image:
    type: user_defined_image_list
    values:
       - harbor.gemini.com:30003/test/e-v4.7.12:v1
  nfssourceip:
    type: string
  nfssourcepath:
    type: string
  nfsmountpath:
    type: string
  flavor:
    type: flavor_list
---
apiVersion: v1
kind: ReplicationController
metadata:
 name: name
 namespace: namespace
spec:
 replicas: 1
 selector:
  "app": "nginx"
 template:
  metadata:
   name: name
   namespace: namespace
   labels:
    "app": "nginx"
  spec:
   containers:
   - name: myweb
     image: {{ image }}
     env:
     - name: password
       value: "password"
     ports:
     - containerPort: 22
       name: ssh
     {%- if nfsmountpath and nfssourceip and nfssourcepath %}
     volumeMounts:
        - mountPath: {{nfsmountpath}}
          name: nfs
          readOnly: false
     {%- endif %}
     resources: {{ flavor }}
   {%- if nfsmountpath and nfssourceip and nfssourcepath %}
   volumes:
     - name: nfs
       nfs:
         server: {{nfssourceip}}
         path: {{nfssourcepath}}
   {%- endif %}
---
apiVersion: v1
kind: Service
metadata:
 name: name
 namespace: namespace
spec:
 type: NodePort
 ports:
 - port: 22
   targetPort: 22
   protocol: TCP
   name: ssh
 selector:
  'app': 'nginx'
