name: Docker Image CI

on:
  #push:
    #branches: [ master ]
  #pull_request:
    #branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: docker login --username=yusongwang1991 --password=${{secrets.password}}
    - name: Start to Build2
      run:  cd F-PyCharm/Dockerfile && docker build -t yusongwang1991/f-pycharm:v1 . --no-cache
    - name: docer push f-pycharm
      run:  docker push yusongwang1991/f-pycharm:v1
    #- name: Start to Build
    #  run:  cd A-tensorflow-gpu-v2.0.0/Dockerfile && docker build -t yusongwang1991/a-tensorflow-gpu-v2.0.0:v1 . --no-cache
    #- name: docer push 
    #  run:  docker push yusongwang1991/a-tensorflow-gpu-v2.0.0:v1
      
      
      
  #      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
