name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: echo $test
    #- name: Start to Build
    #  run:  cd A-tensorflow-gpu-v2.0.0/Dockerfile && docker build -t harbor.gemini.com:30003/test/a-tensorflow-gpu-v2.0.0:v1 . --no-cache
      
      
      
  #      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
