name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Move to the Dockerfile
      run: cd A-tensorflow-gpu-v2.0.0
      
      
      
  #      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
